name: Run Jupyter notebook test

on:
  schedule:
    - cron:  '0 0 * * *'  # This will run the workflow every day at midnight
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter numpy pandas matplotlib scikit-learn beautifulsoup4
        # Add any other dependencies your notebook needs

    - name: Run Python code
      run: py random-forest.py
